In [125]:
import warnings
warnings.filterwarnings("ignore")
import regex

import pandas as pd
import os

In [126]:
df_metadados = pd.DataFrame()
path = '/Users/kpaul/OneDrive/code/github/Project/data_analysis/OLX/dados/'

for arquivo in os.listdir(path):
    print(arquivo)
    df_metadados = pd.concat([df_metadados, pd.read_csv(path + arquivo)])
    
df_metadados.reset_index(drop=True,inplace=True)

metadados_olx_celulares_202210010816.csv
metadados_olx_celulares_202210010817.csv
metadados_olx_celulares_202210010818.csv
metadados_olx_celulares_202210010819.csv
metadados_olx_celulares_202210010820.csv
metadados_olx_celulares_202210010821.csv
metadados_olx_celulares_202210010822.csv
metadados_olx_celulares_202210010823.csv
metadados_olx_celulares_202210010824.csv

In [127]:
df_metadados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25250 entries, 0 to 25249
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     25250 non-null  int64
 1   TITULO                 25250 non-null  object
 2   VALOR                  24443 non-null  object
 3   LOCAL                  25250 non-null  object
 4   DATA_ANUNCIO           25250 non-null  object
 5   LINK                   25250 non-null  object
 6   DATA_COLETA_METADADOS  25250 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.3+ MB

In [128]:
df_metadados2 = df_metadados.drop_duplicates(subset=['ID'])
df_metadados.reset_index(drop=True,inplace=True)
print(df_metadados2.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4805 entries, 0 to 25249
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4805 non-null   int64
 1   TITULO                 4805 non-null   object
 2   VALOR                  4639 non-null   object
 3   LOCAL                  4805 non-null   object
 4   DATA_ANUNCIO           4805 non-null   object
 5   LINK                   4805 non-null   object
 6   DATA_COLETA_METADADOS  4805 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.3+ KB
None

In [129]:
dados = df_metadados2.copy()
(dados.isnull().sum()/len(dados)*100).sort_values(ascending=False)

VALOR                    3.454735
ID                       0.000000
TITULO                   0.000000
LOCAL                    0.000000
DATA_ANUNCIO             0.000000
LINK                     0.000000
DATA_COLETA_METADADOS    0.000000
dtype: float64

In [130]:
dados

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1091450338,"fonte chaveada 50 amperes novas garantia ,entrega",R$ 49,Serra - ES,"Hoje, 08:07",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-01
1,1091450334,iPhone XR 128gb IMPECÁVEL,R$ 2.300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",R$ 1.100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
3,1091450325,Samsung A02 impecável,R$ 350,Rio de Janeiro - RJ,"Hoje, 08:07",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,R$ 950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01
...,...,...,...,...,...,...,...
25245,1091426467,Vendo,R$ 80,Boa Vista - RR,"Hoje, 06:00",https://rr.olx.com.br/roraima/computadores-e-a...,2022-10-01
25246,1091426468,Acessórios e jogos de ps3 original,"R$ 10010x de R$ 10,00",Jaboatão dos Guararapes - PE,"Hoje, 06:00",https://pe.olx.com.br/grande-recife/videogames...,2022-10-01
25247,1091426473,Samsung J7 Prime,"R$ 45012x de R$ 37,50",Nova Friburgo - RJ,"Hoje, 06:00",https://rj.olx.com.br/norte-do-estado-do-rio/c...,2022-10-01
25248,1091426474,Notebook Lenovo i3 6 geração funcionando tudo ...,R$ 1.100,Jaboatão dos Guararapes - PE,"Hoje, 06:00",https://pe.olx.com.br/grande-recife/computador...,2022-10-01
25249,1091426476,Oferta: Samsung Galaxy S20 Plus Cinza - Lindo!,R$ 2.400,Belo Horizonte - MG,"Hoje, 06:00",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-01

In [131]:
dados.dropna(subset = ['VALOR'], inplace = True)
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1091450338,"fonte chaveada 50 amperes novas garantia ,entrega",R$ 49,Serra - ES,"Hoje, 08:07",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-01
1,1091450334,iPhone XR 128gb IMPECÁVEL,R$ 2.300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",R$ 1.100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
3,1091450325,Samsung A02 impecável,R$ 350,Rio de Janeiro - RJ,"Hoje, 08:07",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,R$ 950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01

In [132]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4639 entries, 0 to 25249
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4639 non-null   int64
 1   TITULO                 4639 non-null   object
 2   VALOR                  4639 non-null   object
 3   LOCAL                  4639 non-null   object
 4   DATA_ANUNCIO           4639 non-null   object
 5   LINK                   4639 non-null   object
 6   DATA_COLETA_METADADOS  4639 non-null   object
dtypes: int64(1), object(6)
memory usage: 289.9+ KB

# Trabalhando na coluna valor
Objetivo é deixar essa coluna em formato int e dropar valores estranhos

In [133]:
# tirando o simbolo do reais
val = dados['VALOR'].str.split(' ', expand=True)
dados['VALOR'] = val[1]
dados

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1091450338,"fonte chaveada 50 amperes novas garantia ,entrega",49,Serra - ES,"Hoje, 08:07",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-01
1,1091450334,iPhone XR 128gb IMPECÁVEL,2.300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",1.100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
3,1091450325,Samsung A02 impecável,350,Rio de Janeiro - RJ,"Hoje, 08:07",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01
...,...,...,...,...,...,...,...
25245,1091426467,Vendo,80,Boa Vista - RR,"Hoje, 06:00",https://rr.olx.com.br/roraima/computadores-e-a...,2022-10-01
25246,1091426468,Acessórios e jogos de ps3 original,10010x,Jaboatão dos Guararapes - PE,"Hoje, 06:00",https://pe.olx.com.br/grande-recife/videogames...,2022-10-01
25247,1091426473,Samsung J7 Prime,45012x,Nova Friburgo - RJ,"Hoje, 06:00",https://rj.olx.com.br/norte-do-estado-do-rio/c...,2022-10-01
25248,1091426474,Notebook Lenovo i3 6 geração funcionando tudo ...,1.100,Jaboatão dos Guararapes - PE,"Hoje, 06:00",https://pe.olx.com.br/grande-recife/computador...,2022-10-01
25249,1091426476,Oferta: Samsung Galaxy S20 Plus Cinza - Lindo!,2.400,Belo Horizonte - MG,"Hoje, 06:00",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-01

In [134]:
#suprimindo todos os pontos
a = dados['VALOR']
lista = [ str(i).replace('.' ,'') for i in  a]
dados['VALOR'] = lista
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1091450338,"fonte chaveada 50 amperes novas garantia ,entrega",49,Serra - ES,"Hoje, 08:07",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-01
1,1091450334,iPhone XR 128gb IMPECÁVEL,2300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",1100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
3,1091450325,Samsung A02 impecável,350,Rio de Janeiro - RJ,"Hoje, 08:07",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01

In [135]:
dados['VALOR'].unique()

array(['49', '2300', '1100', '350', '950', '200', '1700', '29012x',
       '3550', '50', '808x', '150', '2091', '80', '30', '320012x',
       '430012x', '1780', '1799', '32', '2700', '160012x', '299012x',
       '230', '375', '300', '100', '2299', '120', '600', '280012x',
       '420012x', '1719', '200012x', '400', '1800', '1200', '2849', '450',
       '115', '1000', '279', '757x', '22012x', '220012x', '120012x',
       '899', '5798', '550', '2599', '365', '130012x', '90', '60012x',
       '310012x', '5499', '289912x', '30012x', '800', '650', '420', '1',
       '219', '145012x', '53912x', '180', '799', '5300', '1899',
       '235012x', '199012x', '565012x', '3900', '1990', '4999', '2799',
       '6299', '189912x', '4000', '3250', '40', '1900', '80012x', '2550',
       '4499', '10010x', '3500', '890000', '2750000', '33333333',
       '2000000', '32000', '15000', '16000', '9000', '1500000', '10999',
       '1300', '3799', '707x', '2500', '3000', '440', '2190', '6699',
       '1999', '700', '16912x', '70', '250', '2690', '199', '580', '7199',
       '210', '6700', '2900', '3100', '3999', '209912x', '350012x', '140',
       '1450', '29', '900', '620', '750', '101x', '3300', '50012x', '850',
       '599', '549', '280', '1400', '6800', '150012x', '680', '89012x',
       '2100', '979x', '1350', '250012x', '1600', '1598', '1500',
       '170012x', '60', '46512x', '399', '149912x', '149', '780', '1599',
       '500', '100012x', '299', '25012x', '190012x', '400012x', '28012x',
       '20012x', '880', '230012x', '2000', '349', '1699', '1499', '35',
       '429', '3998', '5750', '19', '165012x', '110012x', '300012x',
       '829', '909x', '570', '720', '22', '330', '10', '1430', '38512x',
       '1230', '5000', '1650', '14012x', '25', '179912x', '1080', '2450',
       '94912x', '530', '93012x', '252x', '121x', '4800', '20', '480',
       '345012x', '1250', '380', '505x', '35012x', '303x', '1849',
       '55012x', '454x', '2600', '12012x', '390', '140012x', '1550',
       '2050', '606x', '18012x', '370', '115012x', '430', '1399', '0',
       '3299', '15012x', '5500', '220', '23012x', '85', '75', '749',
       '520012x', '95012x', '7900', '6500', '519912x', '185', '3949',
       '449', '460', '1549', '130', '2199', '89912x', '48012x', '270',
       '40012x', '180012x', '999', '269012x', '99', '110', '175012x',
       '310', '75012x', '699', '1850', '34912x', '1770', '730', '85012x',
       '3050', '26512x', '160', '890', '910', '39012x', '45', '6199',
       '3200', '11011x', '1380', '70012x', '2999', '2400', '555x',
       '13912x', '65', '353x', '940', '190', '790', '439912x', '169012x',
       '455', '389912x', '689912x', '1180', '2200', '2350', '4399',
       '45012x', '1320', '98012x', '2099', '379912x', '385', '23912x',
       '2699', '349912x', '740', '86012x', '5299', '270012x', '470',
       '7500', '777', '7049', '353312x', '1299', '1950', '13012x', '1090',
       '550012x', '34012x', '92', '10000', '999x', '4299', '16512x',
       '539912x', '4599', '55', '3249', '16799', '332512x', '1490',
       '5599', '1001', '1119', '79', '1390', '360012x', '269', '195',
       '4500', '1690', '249', '1199', '2499', '289', '210012x', '1039',
       '419', '800000', '3400', '49912x', '545012x', '2850', '989',
       '2150', '1179', '148', '1349', '15', '2800', '129912x', '239912x',
       '202x', '560', '125', '369', '1769', '24912x', '500012x', '4100',
       '119', '18512x', '67912x', '12', '3800', '69912x', '48912x',
       '4300', '7000', '18', '670', '6400', '240012x', '1280', '2250',
       '1120', '175', '1249', '395012x', '599012x', '5790', '2780', '499',
       '21012x', '320', '3199', '90012x', '78', '65912x', '8200', '4699',
       '3370', '1099', '2898', '36012x', '16012x', '11000', '69', '690',
       '159', '14912x', '299912x', '79912x', '1150', '6550', '1050',
       '7598', '930', '229', '789', '169912x', '5199', '1620', '898x',
       '8', '260', '404x', '1649', '185012x', '155012x', '4898', '3',
       '240', '3090', '124912x', '3600', '151x', '2140', '340012x',
       '7499', '619012x', '255012x', '58012x', '1830', '373x', '579',
       '14712x', '1590', '99912x', '5900', '3080', '2750', '4850', '1750',
       '439', '4200', '7750', '3832', '5399', '25000', '6200', '7300',
       '8999', '179', '2390', '7150', '355', '329', '2997', '2650', '123',
       '3150', '6650', '29912x', '125012x', '2399', '254512x', '7999',
       '3850', '189', '9980', '14512x', '3899', '59012x', '91012x',
       '100000', '290012x', '590', '66012x', '139912x', '520', '27012x',
       '7940', '95', '630', '7050', '65012x', '17012x', '159012x', '105',
       '7200', '275012x', '4400', '135', '10510x', '5800', '489',
       '69012x', '17912x', '10100', '215012x', '539012x', '4600',
       '29512x', '700012x', '529912x', '315012x', '580012x', '139',
       '380012x', '499912x', '170', '260012x', '59912x', '19912x', '8000',
       '3490', '13112x', '9500', '9100', '105012x', '114912x', '4797',
       '3350', '7600', '187512x', '3290', '31912x', '9900', '169',
       '680012x', '38012x', '265012x', '109912x', '440012x', '6750',
       '195012x', '138', '5990', '119912x', '285012x', '249012x', '4550',
       '949', '6749', '198012x', '199912x', '480012x', '47012x', '696x',
       '6000', '6900', '3499', '980', '265', '325012x', '25912x',
       '25512x', '5100', '390012x', '2249', '138012x', '28', '290',
       '232x', '225', '135012x', '285', '6499', '162712x', '75912x',
       '4250', '17', '74912x', '679912x', '849', '179012x', '119012x',
       '316112x', '6999', '68012x', '2899', '5', '245', '640', '42012x',
       '14', '339912x', '589', '129012x', '990', '6050', '2015', '24012x',
       '2115', '1715', '7', '165', '1075', '6195', '219012x', '189012x',
       '6300', '109012x', '197012x', '149012x', '1965', '5350', '198912x',
       '249912x', '76912x', '139512x', '2289', '37012x', '17512x', '1097',
       '4199', '52012x', '199712x', '7800', '1790', '599912x', '760',
       '330012x', '58512x', '32012x', '2990', '19012x', '1680', '3599',
       '30007809', '8300', '225012x', '63012x', '33012x', '11999',
       '72038', '8799', '10299', '185000', '9599', '9690', '11500',
       '10990', '10800', '160000', '12800', '81999', '899000', '9999',
       '680006', '1100000', '2650000', '11699', '2900000', '9299',
       '12000', '700000', '9200', '49000', '9899', '11811x', '76012x',
       '4150', '27512x', '124012x', '525x', '44912x', '540012x', '109',
       '26012x', '77012x', '767x', '14000', '410012x', '399012x', '2950',
       '656x', '1220', '425012x', '4899', '18912x', '44412x', '50000',
       '8399', '60000', '177', '3700', '278', '495', '4049', '600012x',
       '8590', '34512x', '229012x', '650012x', '840', '37', '83012x',
       '1049', '3099', '1449', '104912x', '76812x', '699512x', '1070',
       '89', '2630', '1480', '4700', '1640', '191x', '6250', '1890',
       '1170'], dtype=object)

In [136]:
#suprimindo valores em formato de parcela ou seja que contem um "x"
dados2 = dados[dados['VALOR'].str.contains('x')== False]
dados2.head(20)

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1091450338,"fonte chaveada 50 amperes novas garantia ,entrega",49,Serra - ES,"Hoje, 08:07",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-01
1,1091450334,iPhone XR 128gb IMPECÁVEL,2300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",1100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
3,1091450325,Samsung A02 impecável,350,Rio de Janeiro - RJ,"Hoje, 08:07",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01
5,1091450318,Impressora de Fotos Digitais Kodak EasyShare PD3,200,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/audio...,2022-10-01
6,1091450316,Tv samsung 50 funcionando perfeito .,1700,Brasília - DF,"Hoje, 08:07",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-01
8,1055367836,"IPhone 12 64gb , passo cartão em 18x",3550,Goiânia - GO,"Hoje, 08:06",https://go.olx.com.br/grande-goiania-e-anapoli...,2022-10-01
9,1091450301,Suporte Base Com Cooler Para Notebook Leds Verdes,50,São José dos Pinhais - PR,"Hoje, 08:06",https://pr.olx.com.br/regiao-de-curitiba-e-par...,2022-10-01
11,1091450292,Camera ip 360° wifi visão noturna uso interno ...,150,Praia Grande - SP,"Hoje, 08:06",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-01
12,851764648,Cadeira Gamer DarkFlash Preto/Laranja - RC-800...,2091,Florianópolis - SC,"Hoje, 08:06",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-01
13,1091450264,Novo - Smartwatch na caixa completo estilo app...,80,São Luís - MA,"Hoje, 08:06",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-01
14,1091450256,Câmera de Segurança Interna EzViz C1C 1MP Wi-F...,200,Joinville - SC,"Hoje, 08:06",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
15,1091450250,Cabo tipo C,30,Governador Valadares - MG,"Hoje, 08:06",https://mg.olx.com.br/regiao-de-governador-val...,2022-10-01
18,1063598791,Notebook Lenovo Intel i3 i5 i7 Fhd 6ª 7ª 8ªg ...,1780,Curitiba - PR,"Hoje, 08:06",https://pr.olx.com.br/regiao-de-curitiba-e-par...,2022-10-01
19,1088867991,Xbox série S,1799,Belém - PA,"Hoje, 08:06",https://pa.olx.com.br/regiao-de-belem/videogam...,2022-10-01
20,1091450233,Pendrive 32GB Guitarra Novo,32,Joinville - SC,"Hoje, 08:05",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
21,1091450222,Vendo Iphone 11,2700,Rio de Janeiro - RJ,"Hoje, 08:05",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
23,1056012090,"IPhone 12 64gb , 128gb / faça seu orçamento ..",3550,Goiânia - GO,"Hoje, 08:05",https://go.olx.com.br/grande-goiania-e-anapoli...,2022-10-01
25,1091450183,Cpu core 2 duo com 500 GB HD windows 7,230,Suzano - SP,"Hoje, 08:05",https://sp.olx.com.br/sao-paulo-e-regiao/compu...,2022-10-01

In [137]:
dados2['VALOR'].unique()

array(['49', '2300', '1100', '350', '950', '200', '1700', '3550', '50',
       '150', '2091', '80', '30', '1780', '1799', '32', '2700', '230',
       '375', '300', '100', '2299', '120', '600', '1719', '400', '1800',
       '1200', '2849', '450', '115', '1000', '279', '899', '5798', '550',
       '2599', '365', '90', '5499', '800', '650', '420', '1', '219',
       '180', '799', '5300', '1899', '3900', '1990', '4999', '2799',
       '6299', '4000', '3250', '40', '1900', '2550', '4499', '3500',
       '890000', '2750000', '33333333', '2000000', '32000', '15000',
       '16000', '9000', '1500000', '10999', '1300', '3799', '2500',
       '3000', '440', '2190', '6699', '1999', '700', '70', '250', '2690',
       '199', '580', '7199', '210', '6700', '2900', '3100', '3999', '140',
       '1450', '29', '900', '620', '750', '3300', '850', '599', '549',
       '280', '1400', '6800', '680', '2100', '1350', '1600', '1598',
       '1500', '60', '399', '149', '780', '1599', '500', '299', '880',
       '2000', '349', '1699', '1499', '35', '429', '3998', '5750', '19',
       '829', '570', '720', '22', '330', '10', '1430', '1230', '5000',
       '1650', '25', '1080', '2450', '530', '4800', '20', '480', '1250',
       '380', '1849', '2600', '390', '1550', '2050', '370', '430', '1399',
       '0', '3299', '5500', '220', '85', '75', '749', '7900', '6500',
       '185', '3949', '449', '460', '1549', '130', '2199', '270', '999',
       '99', '110', '310', '699', '1850', '1770', '730', '3050', '160',
       '890', '910', '45', '6199', '3200', '1380', '2999', '2400', '65',
       '940', '190', '790', '455', '1180', '2200', '2350', '4399', '1320',
       '2099', '385', '2699', '740', '5299', '470', '7500', '777', '7049',
       '1299', '1950', '1090', '92', '10000', '4299', '4599', '55',
       '3249', '16799', '1490', '5599', '1001', '1119', '79', '1390',
       '269', '195', '4500', '1690', '249', '1199', '2499', '289', '1039',
       '419', '800000', '3400', '2850', '989', '2150', '1179', '148',
       '1349', '15', '2800', '560', '125', '369', '1769', '4100', '119',
       '12', '3800', '4300', '7000', '18', '670', '6400', '1280', '2250',
       '1120', '175', '1249', '5790', '2780', '499', '320', '3199', '78',
       '8200', '4699', '3370', '1099', '2898', '11000', '69', '690',
       '159', '1150', '6550', '1050', '7598', '930', '229', '789', '5199',
       '1620', '8', '260', '1649', '4898', '3', '240', '3090', '3600',
       '2140', '7499', '1830', '579', '1590', '5900', '3080', '2750',
       '4850', '1750', '439', '4200', '7750', '3832', '5399', '25000',
       '6200', '7300', '8999', '179', '2390', '7150', '355', '329',
       '2997', '2650', '123', '3150', '6650', '2399', '7999', '3850',
       '189', '9980', '3899', '100000', '590', '520', '7940', '95', '630',
       '7050', '105', '7200', '4400', '135', '5800', '489', '10100',
       '4600', '139', '170', '8000', '3490', '9500', '9100', '4797',
       '3350', '7600', '3290', '9900', '169', '6750', '138', '5990',
       '4550', '949', '6749', '6000', '6900', '3499', '980', '265',
       '5100', '2249', '28', '290', '225', '285', '6499', '4250', '17',
       '849', '6999', '2899', '5', '245', '640', '14', '589', '990',
       '6050', '2015', '2115', '1715', '7', '165', '1075', '6195', '6300',
       '1965', '5350', '2289', '1097', '4199', '7800', '1790', '760',
       '2990', '1680', '3599', '30007809', '8300', '11999', '72038',
       '8799', '10299', '185000', '9599', '9690', '11500', '10990',
       '10800', '160000', '12800', '81999', '899000', '9999', '680006',
       '1100000', '2650000', '11699', '2900000', '9299', '12000',
       '700000', '9200', '49000', '9899', '4150', '109', '14000', '2950',
       '1220', '4899', '50000', '8399', '60000', '177', '3700', '278',
       '495', '4049', '8590', '840', '37', '1049', '3099', '1449', '1070',
       '89', '2630', '1480', '4700', '1640', '6250', '1890', '1170'],
      dtype=object)

In [138]:
# agora vamos colocar a coluna em formato int
dados2['VALOR'] = dados2['VALOR'].astype('int')
dados2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3554 entries, 0 to 25249
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     3554 non-null   int64
 1   TITULO                 3554 non-null   object
 2   VALOR                  3554 non-null   int32
 3   LOCAL                  3554 non-null   object
 4   DATA_ANUNCIO           3554 non-null   object
 5   LINK                   3554 non-null   object
 6   DATA_COLETA_METADADOS  3554 non-null   object
dtypes: int32(1), int64(1), object(5)
memory usage: 208.2+ KB

In [140]:
dados2 = dados2[(dados2['VALOR'] > 500) & (dados2['VALOR'] <= 15000) ]
dados2

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
1,1091450334,iPhone XR 128gb IMPECÁVEL,2300,São Paulo - SP,"Hoje, 08:07",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-01
2,1091450330,"Monitor Gamer Pichau 24"" Full HD cepheus F24M ...",1100,Joinville - SC,"Hoje, 08:07",https://sc.olx.com.br/norte-de-santa-catarina/...,2022-10-01
4,1091450323,Placa de vídeo RX 480 8gb,950,Manaus - AM,"Hoje, 08:07",https://am.olx.com.br/regiao-de-manaus/computa...,2022-10-01
6,1091450316,Tv samsung 50 funcionando perfeito .,1700,Brasília - DF,"Hoje, 08:07",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-01
8,1055367836,"IPhone 12 64gb , passo cartão em 18x",3550,Goiânia - GO,"Hoje, 08:06",https://go.olx.com.br/grande-goiania-e-anapoli...,2022-10-01
...,...,...,...,...,...,...,...
25235,1091426455,XBOX ONE FAT 500GB + KINECT + JUSTDACE,1100,Nilópolis - RJ,"Hoje, 06:00",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-01
25241,1091426463,PS5 MÍDIA FÍSICA NA GARANTIA,4000,João Pessoa - PB,"Hoje, 06:00",https://pb.olx.com.br/paraiba/videogames/ps5-m...,2022-10-01
25244,1091426466,iPhone X 64g,1700,Manaus - AM,"Hoje, 06:00",https://am.olx.com.br/regiao-de-manaus/celular...,2022-10-01
25248,1091426474,Notebook Lenovo i3 6 geração funcionando tudo ...,1100,Jaboatão dos Guararapes - PE,"Hoje, 06:00",https://pe.olx.com.br/grande-recife/computador...,2022-10-01
25249,1091426476,Oferta: Samsung Galaxy S20 Plus Cinza - Lindo!,2400,Belo Horizonte - MG,"Hoje, 06:00",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-01