In [71]:
import warnings
warnings.filterwarnings("ignore")
import regex
import seaborn as sns
import pandas as pd
import os

In [72]:
df_metadados = pd.DataFrame()
path = '/Users/kpaul/OneDrive/code/github/Project/data_analysis/OLX/dados/'

for arquivo in os.listdir(path):
    print(arquivo)
    df_metadados = pd.concat([df_metadados, pd.read_csv(path + arquivo)])
    
df_metadados.reset_index(drop=True,inplace=True)

metadados_olx_telephones_202210232103.csv
metadados_olx_telephones_202210232104.csv
metadados_olx_telephones_202210232105.csv
metadados_olx_telephones_202210232106.csv
metadados_olx_telephones_202210232107.csv
metadados_olx_telephones_202210232108.csv

In [73]:
df_metadados2 = df_metadados.drop_duplicates(subset=['ID'])
df_metadados.reset_index(drop=True,inplace=True)
print(df_metadados2.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 16809
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4809 non-null   int64
 1   TITULO                 4809 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4809 non-null   object
 4   DATA_ANUNCIO           4809 non-null   object
 5   LINK                   4809 non-null   object
 6   DATA_COLETA_METADADOS  4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB
None

In [74]:
dados = df_metadados2.copy()
(dados.isnull().sum()/len(dados)*100).sort_values(ascending=False)

VALOR                    1.91308
ID                       0.00000
TITULO                   0.00000
LOCAL                    0.00000
DATA_ANUNCIO             0.00000
LINK                     0.00000
DATA_COLETA_METADADOS    0.00000
dtype: float64

In [75]:
dados = dados.reset_index(drop=True)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4809 non-null   int64
 1   TITULO                 4809 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4809 non-null   object
 4   DATA_ANUNCIO           4809 non-null   object
 5   LINK                   4809 non-null   object
 6   DATA_COLETA_METADADOS  4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [76]:
dados.dropna(subset = ['VALOR'], inplace = True)
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",R$ 6.000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,R$ 650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,R$ 900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,R$ 450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,R$ 2.380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23

In [77]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
dtypes: int64(1), object(6)
memory usage: 294.8+ KB

# Trabalhando na coluna valor
Objetivo é deixar essa coluna em formato int e dropar valores estranhos

In [78]:
# tirando o simbolo do reais
val = dados['VALOR'].str.split(' ', expand=True)
dados['VALOR'] = val[1]
dados

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6.000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2.380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
...,...,...,...,...,...,...,...
4804,1100722954,Vendo esse j8,250,Rio Branco - AC,"Hoje, 19:40",https://ac.olx.com.br/acre/celulares/vendo-ess...,2022-10-23
4805,1100722956,iPhone 8 Plus novo,2.100,São Luís - MA,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23
4806,1100722960,Moto g8,270,Sorocaba - SP,"Hoje, 19:40",https://sp.olx.com.br/regiao-de-sorocaba/celul...,2022-10-23
4807,1100722961,G30,0,São Luís - MA,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23
4808,1100722972,Samsung A80 ótimo estado,1.200,Praia Grande - SP,"Hoje, 19:40",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-23

In [79]:
#suprimindo todos os pontos
a = dados['VALOR']
lista = [ str(i).replace('.' ,'') for i in  a]
dados['VALOR'] = lista
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23

In [80]:
#suprimindo valores em formato de parcela ou seja que contem um "x"
dados = dados[dados['VALOR'].str.contains('x')== False]
dados.head(20)

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
5,1100742865,iPhone 7plus,920,Campinas - SP,"Hoje, 20:54",https://sp.olx.com.br/grande-campinas/celulare...,2022-10-23
6,1037408731,IPHONE XSMAX 256 GB SEMI NOVOS DE VITRINE COM ...,3350,Belo Horizonte - MG,"Hoje, 20:54",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
7,1058809777,iPhone X 64Gb Seminovo,2399,Porto Alegre - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
8,1100742843,iPhone 8 Plus 128gb 88 de bateria,1300,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
9,1100742837,iPhone 11 64 GB novo,2990,Santo Amaro da Imperatriz - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
10,1023389133,IPHONE XS MAX 64 GB SEMI NOVOS,3250,Belo Horizonte - MG,"Hoje, 20:54",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
11,1100742834,Iphone 6s,350,Juiz de Fora - MG,"Hoje, 20:54",https://mg.olx.com.br/regiao-de-juiz-de-fora/c...,2022-10-23
12,1100742828,Vendo Edge 20 Pro (256 gb),2300,Rio de Janeiro - RJ,"Hoje, 20:53",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
13,1073057148,"Apple Watch 7 Até 12X ( Super Promoção Hoje, T...",2380,Brasília - DF,"Hoje, 20:53",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
14,1100742740,iPhone 12 128GB,3600,Nova Iguaçu - RJ,"Hoje, 20:53",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
15,1100742725,Iphone 7,800,Olinda - PE,"Hoje, 20:53",https://pe.olx.com.br/grande-recife/celulares/...,2022-10-23
16,1100742695,iPhone 11 64 GB lacrado,3000,Juiz de Fora - MG,"Hoje, 20:53",https://mg.olx.com.br/regiao-de-juiz-de-fora/c...,2022-10-23
17,1100742659,iPhone 11 + fone de ouvido sem fio !,2800,Brasília - DF,"Hoje, 20:53",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
18,1100742633,Iphone XR 128gb - Branco,2867,Contagem - MG,"Hoje, 20:53",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
20,1099573952,Samsung S21 FE 5G na caixa com NF,3900,Manaus - AM,"Hoje, 20:52",https://am.olx.com.br/regiao-de-manaus/celular...,2022-10-23

In [81]:
# agora vamos colocar a coluna em formato int
dados['VALOR'] = dados['VALOR'].astype('int')
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   int32
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
dtypes: int32(1), int64(1), object(5)
memory usage: 276.4+ KB

In [82]:
#dados = dados[(dados2['VALOR'] > 500) & (dados2['VALOR'] <= 15000) ]
#dados

In [83]:
dados['LOCAL'] = dados['LOCAL'].str.lower()
a = dados['LOCAL'].str[-2:]
dados['Estado'] = a
dados

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS,Estado
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,rio de janeiro - rj,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23,rj
1,1100742919,Motorola Moto G7 Play,650,canoas - rs,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23,rs
2,1100742895,iPhone,900,salvador - ba,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23,ba
3,1100742892,Iphone 6s,450,palhoça - sc,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23,sc
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,brasília - df,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23,df
...,...,...,...,...,...,...,...,...
4804,1100722954,Vendo esse j8,250,rio branco - ac,"Hoje, 19:40",https://ac.olx.com.br/acre/celulares/vendo-ess...,2022-10-23,ac
4805,1100722956,iPhone 8 Plus novo,2100,são luís - ma,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23,ma
4806,1100722960,Moto g8,270,sorocaba - sp,"Hoje, 19:40",https://sp.olx.com.br/regiao-de-sorocaba/celul...,2022-10-23,sp
4807,1100722961,G30,0,são luís - ma,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23,ma
4808,1100722972,Samsung A80 ótimo estado,1200,praia grande - sp,"Hoje, 19:40",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-23,sp

In [84]:
dados['TITULO'] = dados['TITULO'].str.lower()
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   int32
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
 7   Estado                 4717 non-null   object
dtypes: int32(1), int64(1), object(6)
memory usage: 313.2+ KB

In [85]:
#marcas = ["samsung", "xiaomi", "apple", "iphone" , "motorola", "asus", "lg", "huawei", "lenovo", "nokia"]
lista = []
for i in dados["TITULO"]:
    if "iphone" in i or "apple" in i:
       lista.append("Iphone")
    elif "samsung" in i:
        lista.append("Samsung")
    elif "xiaomi" in i:
        lista.append("Xiaomi")
    elif "lg" in i:
        lista.append("Lg")
    elif "motorola" in i or "moto" in i :
        lista.append("Motorola")
    elif "nokia" in i:
        lista.append("Nokia")
    elif "asus" in i:
        lista.append("Asus")
    elif "huawei" in i:
        lista.append("Huawei")
    elif "lenovo" in i:
        lista.append("Lenovo")
    else:
        lista.append("Other")
dados["marcas"] = pd.DataFrame(lista)
dados.sample(100)

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS,Estado,marcas
1001,1097792166,iphone 7 128 gb,750,são caetano do sul - sp,"Hoje, 20:32",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-23,sp,Xiaomi
2666,1100729237,samsung galaxy buds pro,500,uberlândia - mg,"Hoje, 20:03",https://mg.olx.com.br/regiao-de-uberlandia-e-u...,2022-10-23,mg,Other
2485,1100731979,poco f3 capa,30,recife - pe,"Hoje, 20:13",https://pe.olx.com.br/grande-recife/celulares/...,2022-10-23,pe,Motorola
3383,1099120859,cel xiaomi redmi note 11 pro plus 5g 6gb/128gb...,2289,itabirito - mg,"Hoje, 20:01",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23,mg,Motorola
4396,1100728624,samsung galaxy s22 plus,3999,belo horizonte - mg,"Hoje, 20:00",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23,mg,Iphone
...,...,...,...,...,...,...,...,...,...
2312,1100734791,moto g30,800,salvador - ba,"Hoje, 20:22",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23,ba,Iphone
3866,1094013518,iphone xs max 256 gb,3000,rio de janeiro - rj,"Hoje, 20:01",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23,rj,Iphone
4429,1100728013,iphone 7 plus,1100,são josé - sc,"Hoje, 20:00",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23,sc,Samsung
1447,1095329247,iphone 11,2699,juazeiro do norte - ce,"Hoje, 20:31",https://ce.olx.com.br/regiao-de-juazeiro-do-no...,2022-10-23,ce,Samsung
2295,1100735205,troco iphone 7 plus,1500,boa vista - rr,"Hoje, 20:25",https://rr.olx.com.br/roraima/celulares/troco-...,2022-10-23,rr,Samsung

In [86]:
dados.value_counts("marcas")

marcas
Iphone      2091
Other       1199
Samsung      576
Motorola     438
Xiaomi       187
Lg            91
Asus          20
Nokia         17
Lenovo         6
Huawei         3
dtype: int64

In [88]:
ot = dados[dados["marcas"] == "Other"]
ot

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS,Estado,marcas
12,1100742828,vendo edge 20 pro (256 gb),2300,rio de janeiro - rj,"Hoje, 20:53",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23,rj,Other
28,1100037691,carregador iphone 11 pro 12 13 xr 8 plus origi...,195,recife - pe,"Hoje, 20:51",https://pe.olx.com.br/grande-recife/celulares/...,2022-10-23,pe,Other
29,1099107418,celular mi light 10 - 5g,1350,florianópolis - sc,"Hoje, 20:51",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23,sc,Other
33,1100742204,adaptador para carregamento sem fio - indução ...,89,suzano - sp,"Hoje, 20:51",https://sp.olx.com.br/sao-paulo-e-regiao/celul...,2022-10-23,sp,Other
46,817020325,iphone 7 32gb,1599,recife - pe,"Hoje, 20:50",https://pe.olx.com.br/grande-recife/celulares/...,2022-10-23,pe,Other
...,...,...,...,...,...,...,...,...,...
4706,965894045,xiaomi novo com garantia,699,maringá - pr,"Hoje, 19:45",https://pr.olx.com.br/regiao-de-maringa/celula...,2022-10-23,pr,Other
4709,1100724910,motorola moto c plus semi-novo,180,feira de santana - ba,"Hoje, 19:45",https://ba.olx.com.br/regiao-de-feira-de-santa...,2022-10-23,ba,Other
4710,1070535134,corre garantir o presente do paizão,640,maringá - pr,"Hoje, 19:45",https://pr.olx.com.br/regiao-de-maringa/celula...,2022-10-23,pr,Other
4711,1061284821,par de rádios comunicador baofeng walktalk bf-...,159,goiânia - go,"Hoje, 19:45",https://go.olx.com.br/grande-goiania-e-anapoli...,2022-10-23,go,Other
4715,889059198,tela / display para iphone 4 e 4s - instalação...,99,vitória - es,"Hoje, 19:45",https://es.olx.com.br/norte-do-espirito-santo/...,2022-10-23,es,Other

In [89]:
ot.to_excel('others.xlsx')