In [65]:
import warnings
warnings.filterwarnings("ignore")
import regex
import seaborn as sns
import pandas as pd
import os

In [86]:
df_metadados = pd.DataFrame()
path = '/Users/kpaul/OneDrive/code/github/Project/data_analysis/OLX/dados/'

for arquivo in os.listdir(path):
    print(arquivo)
    df_metadados = pd.concat([df_metadados, pd.read_csv(path + arquivo)])
    
df_metadados.reset_index(drop=True,inplace=True)

metadados_olx_telephones_202210232103.csv
metadados_olx_telephones_202210232104.csv
metadados_olx_telephones_202210232105.csv
metadados_olx_telephones_202210232106.csv
metadados_olx_telephones_202210232107.csv
metadados_olx_telephones_202210232108.csv

In [182]:
df_metadados2 = df_metadados.drop_duplicates(subset=['ID'])
df_metadados.reset_index(drop=True,inplace=True)
print(df_metadados2.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4809 non-null   int64
 1   TITULO                 4809 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4809 non-null   object
 4   DATA_ANUNCIO           4809 non-null   object
 5   LINK                   4809 non-null   object
 6   DATA_COLETA_METADADOS  4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB
None

In [183]:
dados = df_metadados2.copy()
(dados.isnull().sum()/len(dados)*100).sort_values(ascending=False)

VALOR                    1.91308
ID                       0.00000
TITULO                   0.00000
LOCAL                    0.00000
DATA_ANUNCIO             0.00000
LINK                     0.00000
DATA_COLETA_METADADOS    0.00000
dtype: float64

In [185]:
dados.shape

(4809, 7)

In [186]:
dados.dropna(subset = ['VALOR'], inplace = True)
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",R$ 6.000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,R$ 650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,R$ 900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,R$ 450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,R$ 2.380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23

In [187]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
dtypes: int64(1), object(6)
memory usage: 294.8+ KB

# Trabalhando na coluna valor
Objetivo é deixar essa coluna em formato int e dropar valores estranhos

In [188]:
# tirando o simbolo do reais
val = dados['VALOR'].str.split(' ', expand=True)
dados['VALOR'] = val[1]
dados

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6.000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2.380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
...,...,...,...,...,...,...,...
4804,1100722954,Vendo esse j8,250,Rio Branco - AC,"Hoje, 19:40",https://ac.olx.com.br/acre/celulares/vendo-ess...,2022-10-23
4805,1100722956,iPhone 8 Plus novo,2.100,São Luís - MA,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23
4806,1100722960,Moto g8,270,Sorocaba - SP,"Hoje, 19:40",https://sp.olx.com.br/regiao-de-sorocaba/celul...,2022-10-23
4807,1100722961,G30,0,São Luís - MA,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23
4808,1100722972,Samsung A80 ótimo estado,1.200,Praia Grande - SP,"Hoje, 19:40",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-23

In [192]:
#suprimindo todos os pontos
a = dados['VALOR']
lista = [ str(i).replace('.' ,'') for i in  a]
dados['VALOR'] = lista
dados.head()

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23

In [193]:
#suprimindo valores em formato de parcela ou seja que contem um "x"
dados2 = dados[dados['VALOR'].str.contains('x')== False]
dados2.head(20)

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
3,1100742892,Iphone 6s,450,Palhoça - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
5,1100742865,iPhone 7plus,920,Campinas - SP,"Hoje, 20:54",https://sp.olx.com.br/grande-campinas/celulare...,2022-10-23
6,1037408731,IPHONE XSMAX 256 GB SEMI NOVOS DE VITRINE COM ...,3350,Belo Horizonte - MG,"Hoje, 20:54",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
7,1058809777,iPhone X 64Gb Seminovo,2399,Porto Alegre - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
8,1100742843,iPhone 8 Plus 128gb 88 de bateria,1300,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
9,1100742837,iPhone 11 64 GB novo,2990,Santo Amaro da Imperatriz - SC,"Hoje, 20:54",https://sc.olx.com.br/florianopolis-e-regiao/c...,2022-10-23
10,1023389133,IPHONE XS MAX 64 GB SEMI NOVOS,3250,Belo Horizonte - MG,"Hoje, 20:54",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
11,1100742834,Iphone 6s,350,Juiz de Fora - MG,"Hoje, 20:54",https://mg.olx.com.br/regiao-de-juiz-de-fora/c...,2022-10-23
12,1100742828,Vendo Edge 20 Pro (256 gb),2300,Rio de Janeiro - RJ,"Hoje, 20:53",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
13,1073057148,"Apple Watch 7 Até 12X ( Super Promoção Hoje, T...",2380,Brasília - DF,"Hoje, 20:53",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
14,1100742740,iPhone 12 128GB,3600,Nova Iguaçu - RJ,"Hoje, 20:53",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
15,1100742725,Iphone 7,800,Olinda - PE,"Hoje, 20:53",https://pe.olx.com.br/grande-recife/celulares/...,2022-10-23
16,1100742695,iPhone 11 64 GB lacrado,3000,Juiz de Fora - MG,"Hoje, 20:53",https://mg.olx.com.br/regiao-de-juiz-de-fora/c...,2022-10-23
17,1100742659,iPhone 11 + fone de ouvido sem fio !,2800,Brasília - DF,"Hoje, 20:53",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
18,1100742633,Iphone XR 128gb - Branco,2867,Contagem - MG,"Hoje, 20:53",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
20,1099573952,Samsung S21 FE 5G na caixa com NF,3900,Manaus - AM,"Hoje, 20:52",https://am.olx.com.br/regiao-de-manaus/celular...,2022-10-23

In [194]:
# agora vamos colocar a coluna em formato int
dados2['VALOR'] = dados2['VALOR'].astype('int')
dados2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   int32
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
dtypes: int32(1), int64(1), object(5)
memory usage: 276.4+ KB

In [79]:
dados2 = dados2[(dados2['VALOR'] > 500) & (dados2['VALOR'] <= 15000) ]
dados2

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,Rio de Janeiro - RJ,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23
1,1100742919,Motorola Moto G7 Play,650,Canoas - RS,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
2,1100742895,iPhone,900,Salvador - BA,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,Brasília - DF,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23
5,1100742865,iPhone 7plus,920,Campinas - SP,"Hoje, 20:54",https://sp.olx.com.br/grande-campinas/celulare...,2022-10-23
...,...,...,...,...,...,...,...
16799,1100723326,iPhone XR,1900,Igaci - AL,"Hoje, 19:40",https://al.olx.com.br/alagoas/celulares/iphone...,2022-10-23
16800,1100723328,iPhone 12 Pro 256GB + caixa e acessórios,4190,Alvorada - RS,"Hoje, 19:40",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23
16801,1100723329,S22 ultra 256GB,4800,Belo Horizonte - MG,"Hoje, 19:40",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23
16806,1100722956,iPhone 8 Plus novo,2100,São Luís - MA,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23
16809,1100722972,Samsung A80 ótimo estado,1200,Praia Grande - SP,"Hoje, 19:40",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-23

In [80]:
dados2['LOCAL'] = dados2['LOCAL'].str.lower()
a = dados2['LOCAL'].str[-2:]
dados2['Estado'] = a
dados2

,ID,TITULO,VALOR,LOCAL,DATA_ANUNCIO,LINK,DATA_COLETA_METADADOS,Estado
0,1099084653,"Iphone 12 Pro Max, 256 GB, Graphite",6000,rio de janeiro - rj,"Hoje, 20:54",https://rj.olx.com.br/rio-de-janeiro-e-regiao/...,2022-10-23,rj
1,1100742919,Motorola Moto G7 Play,650,canoas - rs,"Hoje, 20:54",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23,rs
2,1100742895,iPhone,900,salvador - ba,"Hoje, 20:54",https://ba.olx.com.br/grande-salvador/celulare...,2022-10-23,ba
4,1073862676,Apple Watch 7 Até 12X ( Super Promoção Hoje!! ...,2380,brasília - df,"Hoje, 20:54",https://df.olx.com.br/distrito-federal-e-regia...,2022-10-23,df
5,1100742865,iPhone 7plus,920,campinas - sp,"Hoje, 20:54",https://sp.olx.com.br/grande-campinas/celulare...,2022-10-23,sp
...,...,...,...,...,...,...,...,...
16799,1100723326,iPhone XR,1900,igaci - al,"Hoje, 19:40",https://al.olx.com.br/alagoas/celulares/iphone...,2022-10-23,al
16800,1100723328,iPhone 12 Pro 256GB + caixa e acessórios,4190,alvorada - rs,"Hoje, 19:40",https://rs.olx.com.br/regioes-de-porto-alegre-...,2022-10-23,rs
16801,1100723329,S22 ultra 256GB,4800,belo horizonte - mg,"Hoje, 19:40",https://mg.olx.com.br/belo-horizonte-e-regiao/...,2022-10-23,mg
16806,1100722956,iPhone 8 Plus novo,2100,são luís - ma,"Hoje, 19:40",https://ma.olx.com.br/regiao-de-sao-luis/celul...,2022-10-23,ma
16809,1100722972,Samsung A80 ótimo estado,1200,praia grande - sp,"Hoje, 19:40",https://sp.olx.com.br/baixada-santista-e-litor...,2022-10-23,sp

In [196]:
dados['TITULO'] = dados['TITULO'].str.lower()
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4717 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     4717 non-null   int64
 1   TITULO                 4717 non-null   object
 2   VALOR                  4717 non-null   object
 3   LOCAL                  4717 non-null   object
 4   DATA_ANUNCIO           4717 non-null   object
 5   LINK                   4717 non-null   object
 6   DATA_COLETA_METADADOS  4717 non-null   object
dtypes: int64(1), object(6)
memory usage: 294.8+ KB

In [200]:
#marcas = ["samsung", "xiaomi", "apple", "iphone" , "motorola", "asus", "lg", "huawei", "lenovo", "nokia"]
lista = []
for i in dados["TITULO"]:
    if "iphone" in i or "apple" in i:
       lista.append("Iphone")
    elif "samsung" in i:
        lista.append("Samsung")
    elif "xiaomi" in i:
        lista.append("Xiaomi")
    elif "lg" in i:
        lista.append("Lg")
    elif "motorola" in i or "moto" in i :
        lista.append("Motorola")
    elif "nokia" in i:
        lista.append("Nokia")
    elif "asus" in i:
        lista.append("Asus")
    elif "huawei" in i:
        lista.append("Huawei")
    elif "lenovo" in i:
        lista.append("Lenovo")
    else:
        lista.append("Other")
dados["marcas"] = pd.DataFrame(lista)
dados["TITULO"].shape

(4717,)